{{- if .Values.clusterExternalSecret.enabled }}
{{- $clusterExternalSecretDefaultNamespace := .Values.clusterExternalSecret.namespace }}
{{- $releaseNamespace := .Release.Namespace }}
{{- range $clusterExternalSecret := .Values.clusterExternalSecret.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ $clusterExternalSecret.name }}
  {{- if $clusterExternalSecret.labels }}
  {{- with $clusterExternalSecret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if $clusterExternalSecret.annotations }}
  {{- with $clusterExternalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if $clusterExternalSecret.namespace }}
  namespace: {{ $clusterExternalSecret.namespace }}
  {{- else if $clusterExternalSecretDefaultNamespace }}
  namespace: {{ $clusterExternalSecretDefaultNamespace }}
  {{- else }}
  namespace: {{ $releaseNamespace }}
  {{- end }}
spec:
  {{- if $clusterExternalSecret.externalSecretSpec }}
  externalSecretSpec:
    {{- if $clusterExternalSecret.externalSecretSpec.secretStoreRef }}
    secretStoreRef:
      name: {{ $clusterExternalSecret.externalSecretSpec.secretStoreRef.name }}
      kind: {{ $clusterExternalSecret.externalSecretSpec.secretStoreRef.kind | default "SecretStore" }}
    {{- end }}
    {{- if $clusterExternalSecret.externalSecretSpec.target }}
    target:
      name: {{ $clusterExternalSecret.externalSecretSpec.target.name | default $clusterExternalSecret.externalSecretSpec.name | quote }}
      creationPolicy: {{ $clusterExternalSecret.externalSecretSpec.target.creationPolicy | default "Owner" }}
      deletionPolicy: {{ $clusterExternalSecret.externalSecretSpec.target.deletionPolicy | default "Retain" }}
      {{- if $clusterExternalSecret.externalSecretSpec.target.template }}
      template:
        {{- if $clusterExternalSecret.externalSecretSpec.target.template.type }}
        type: {{ $clusterExternalSecret.externalSecretSpec.target.template.type }}
        {{- end }}
        {{- if $clusterExternalSecret.externalSecretSpec.target.template.engineVersion }}
        engineVersion: {{ $clusterExternalSecret.externalSecretSpec.target.template.engineVersion }}
        {{- end }}
        {{- if $clusterExternalSecret.externalSecretSpec.target.template.metadata }}
        metadata:
          {{- if $clusterExternalSecret.externalSecretSpec.target.template.metadata.labels }}
          {{- with $clusterExternalSecret.externalSecretSpec.target.template.metadata.labels }}
          labels:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if $clusterExternalSecret.externalSecretSpec.target.template.metadata.annotations }}
          {{- with $clusterExternalSecret.externalSecretSpec.target.template.metadata.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- if $clusterExternalSecret.externalSecretSpec.target.template.data }}
        {{- with $clusterExternalSecret.externalSecretSpec.target.template.data }}
        data:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if $clusterExternalSecret.externalSecretSpec.target.template.templateFrom }}
        templateFrom:
        {{- range $templateFrom := $clusterExternalSecret.externalSecretSpec.target.template.templateFrom }}
        {{- if $templateFrom.configMap }}
          - configMap:
              name: {{ $templateFrom.configMap.name }}
              items:
              {{ range $templateFromConfigMapItems := $templateFrom.configMap.items }}
                - key: {{ $templateFromConfigMapItems.key }}
              {{- end }}
        {{- end }}
        {{- if $templateFrom.secret }}
          - secret:
              name: {{ $templateFrom.secret.name }}
              items:
              {{- range $templateFromSecretItems := $templateFrom.secret.items }}
                - key: {{ $templateFromSecretItems.key }}
              {{- end }}
        {{- end }}
        {{- if $templateFrom.scope }}
          scope: {{ $templateFrom.scope }}
        {{- end }}
        {{- if $templateFrom.target }}
          target: {{ $templateFrom.target }}
        {{- end }}
        {{- if $templateFrom.literal }}
          literal: {{ $templateFrom.literal }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- if $clusterExternalSecret.externalSecretSpec.target.immutable }}
      immutable: {{ $clusterExternalSecret.externalSecretSpec.target.immutable }}
      {{- end }}
    {{- end }}
    refreshInterval: {{ $clusterExternalSecret.externalSecretSpec.refreshInterval | default "1h" }}
    {{- if $clusterExternalSecret.externalSecretSpec.data }}
    data:
    {{- range $externalSecretData := $clusterExternalSecret.externalSecretSpec.data }}
      - secretKey: {{ $externalSecretData.secretKey }}
        remoteRef:
          key: {{ $externalSecretData.remoteRef.key }}
          {{- if $externalSecretData.remoteRef.metadataPolicy }}
          metadataPolicy: {{ $externalSecretData.remoteRef.metadataPolicy | default "None" }}
          {{- end }}
          {{- if $externalSecretData.remoteRef.property }}
          property: {{ $externalSecretData.remoteRef.property }}
          {{- end }}
          {{- if $externalSecretData.remoteRef.version }}
          version: {{ $externalSecretData.remoteRef.version }}
          {{- end }}
          {{- if $externalSecretData.remoteRef.conversionStrategy }}
          conversionStrategy: {{ $externalSecretData.remoteRef.conversionStrategy }}
          {{- end }}
          {{- if $externalSecretData.remoteRef.decodingStrategy }}
          decodingStrategy: {{ $externalSecretData.remoteRef.decodingStrategy }}
          {{- end }}
        {{- if $externalSecretData.sourceRef }}
        sourceRef:
          {{- if $externalSecretData.sourceRef.storeRef }}
          storeRef:
            name: {{ $externalSecretData.sourceRef.storeRef.name }}
            kind: {{ $externalSecretData.sourceRef.storeRef.kind | default "SecretStore" }}
          {{- end }}
          {{- if $externalSecretData.sourceRef.generatorRef }}
          generatorRef:
            apiVersion: {{ $externalSecretData.sourceRef.generatorRef.apiVersion }}
            kind: {{ $externalSecretData.sourceRef.generatorRef.kind }}
            name: {{ $externalSecretData.sourceRef.generatorRef.name }}
          {{- end }}
        {{- end }}
    {{- end }}
    {{- if $clusterExternalSecret.dataFrom }}
    dataFrom:
    {{- range $externalSecretDataFrom := $clusterExternalSecret.dataFrom }}
      {{- if $externalSecretDataFrom.sourceRef }}
      - sourceRef:
          {{- if $externalSecretDataFrom.sourceRef.storeRef }}
          storeRef:
            name: {{ $externalSecretDataFrom.sourceRef.storeRef.name }}
            kind: {{ $externalSecretDataFrom.sourceRef.storeRef.kind | default "SecretStore" }}
          {{- end }}
          {{- if $externalSecretDataFrom.sourceRef.generatorRef }}
          generatorRef:
            apiVersion: {{ $externalSecretDataFrom.sourceRef.generatorRef.apiVersion }}
            kind: {{ $externalSecretDataFrom.sourceRef.generatorRef.kind }}
            name: {{ $externalSecretDataFrom.sourceRef.generatorRef.name }}
          {{- end }}
      {{- end }}
      {{- if and $externalSecretDataFrom.extract $externalSecretDataFrom.rewrite }}
      - extract:
          key: {{ $externalSecretDataFrom.extract.key }}
          {{- if $externalSecretDataFrom.extract.metadataPolicy }}
          metadataPolicy: {{ $externalSecretDataFrom.extract.metadataPolicy | default "None" }}
          {{- end }}
          {{- if $externalSecretDataFrom.extract.property }}
          property: {{ $externalSecretDataFrom.extract.property }}
          {{- end }}
          {{- if $externalSecretDataFrom.extract.version }}
          version: {{ $externalSecretDataFrom.extract.version }}
          {{- end }}
          {{- if $externalSecretDataFrom.extract.conversionStrategy }}
          conversionStrategy: {{ $externalSecretDataFrom.extract.conversionStrategy }}
          {{- end }}
          {{- if $externalSecretDataFrom.extract.decodingStrategy }}
          decodingStrategy: {{ $externalSecretDataFrom.extract.decodingStrategy }}
          {{- end }}
        rewrite:
        {{- range $externalSecretDataFromRewrite := $externalSecretDataFrom.rewrite }}
          - regexp:
              source: {{ $externalSecretDataFromRewrite.source }}
              target: {{ $externalSecretDataFromRewrite.target }}
        {{- end }}
      {{- end }}
      {{- if and $externalSecretDataFrom.find $externalSecretDataFrom.rewrite }}
      - find:
          {{- if $externalSecretDataFrom.find.path }}
          path: {{ $externalSecretDataFrom.find.path }}
          {{- end }}
          {{- if $externalSecretDataFrom.find.name }}
          name: {{ $externalSecretDataFrom.find.name }}
          {{- end }}
          {{- if $externalSecretDataFrom.find.tags }}
          {{- with $externalSecretDataFrom.find.tags }}
          tags:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if $externalSecretDataFrom.find.conversionStrategy }}
          conversionStrategy: {{ $externalSecretDataFrom.find.conversionStrategy }}
          {{- end }}
          {{- if $externalSecretDataFrom.find.decodingStrategy }}
          decodingStrategy: {{ $externalSecretDataFrom.find.decodingStrategy }}
          {{- end }}
        rewrite:
        {{- range $externalSecretDataFromRewrite := $externalSecretDataFrom.rewrite }}
          - regexp:
              source: {{ $externalSecretDataFromRewrite.source }}
              target: {{ $externalSecretDataFromRewrite.target }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
  externalSecretName: {{ $clusterExternalSecret.externalSecretName | default $clusterExternalSecret.name }}
  {{- if $clusterExternalSecret.externalSecretMetadata }}
  externalSecretMetadata:
    {{- if $clusterExternalSecret.externalSecretMetadata.annotations }}
    {{- with $clusterExternalSecret.externalSecretMetadata.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- if $clusterExternalSecret.externalSecretMetadata.labels }}
    {{- with $clusterExternalSecret.externalSecretMetadata.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if $clusterExternalSecret.namespaceSelector }}
  namespaceSelector:
    {{- with $clusterExternalSecret.namespaceSelector.matchLabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if $clusterExternalSecret.namespaces }}
  namespaces:
    {{- range $namespace := $clusterExternalSecret.namespaces }}
    - {{ $namespace | quote }}
    {{- end }}
  {{- end }}
  {{- if $clusterExternalSecret.refreshTime }}
  refreshTime: {{ $clusterExternalSecret.refreshTime }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
