{{- if .Values.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  {{- if .Values.clusterSecretStore.labels }}
  {{- with .Values.clusterSecretStore.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.clusterSecretStore.annotations }}
  {{- with .Values.clusterSecretStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.clusterSecretStore.namespace }}
  namespace: {{ .Values.clusterSecretStore.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
spec:
  {{- if .Values.clusterSecretStore.controller }}
  controller: {{ .Values.clusterSecretStore.controller }}
  {{- end }}
  {{- if .Values.clusterSecretStore.provider }}
  {{- with .Values.clusterSecretStore.provider }}
  provider:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.clusterSecretStore.retrySettings }}
  {{- with .Values.clusterSecretStore.retrySettings }}
  retrySettings:
    maxRetries: {{ .maxRetries }}
    retryInterval: {{ .retryInterval | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.clusterSecretStore.refreshInterval }}
  refreshInterval: {{ .Values.clusterSecretStore.refreshInterval }}
  {{- end }}
  {{- if .Values.clusterSecretStore.conditions }}
  conditions:
  {{- range $condition := .Values.clusterSecretStore.conditions }}
    {{- if $condition.namespaceSelector }}
    - namespaceSelector:
        {{- with $condition.namespaceSelector.matchLabels }}
        matchLabels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- end }}
    {{- if $condition.namespaces }}
    - namespaces:
      {{- range $namespace := $condition.namespaces }}
      - {{ $namespace | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
