{{- if .Values.externalSecret.enabled }}
{{- $externalSecretDefaultNamespace := .Values.externalSecret.namespace }}
{{- $releaseNamespace := .Release.Namespace }}
{{- range $externalSecret := .Values.externalSecret.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
  {{- if $externalSecret.labels }}
  {{- with $externalSecret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if $externalSecret.annotations }}
  {{- with $externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if $externalSecret.namespace }}
  namespace: {{ $externalSecret.namespace }}
  {{- else if $externalSecretDefaultNamespace }}
  namespace: {{ $externalSecretDefaultNamespace }}
  {{- else }}
  namespace: {{ $releaseNamespace }}
  {{- end }}
spec:
  {{- if $externalSecret.secretStoreRef }}
  secretStoreRef:
    name: {{ $externalSecret.secretStoreRef.name }}
    kind: {{ $externalSecret.secretStoreRef.kind | default "SecretStore" }}
  {{- end }}
  {{- if $externalSecret.target }}
  target:
    name: {{ $externalSecret.target.name | default $externalSecret.name | quote }}
    creationPolicy: {{ $externalSecret.target.creationPolicy | default "Owner" }}
    deletionPolicy: {{ $externalSecret.target.deletionPolicy | default "Retain" }}
    {{- if $externalSecret.target.template }}
    template:
      {{- if $externalSecret.target.template.type }}
      type: {{ $externalSecret.target.template.type }}
      {{- end }}
      {{- if $externalSecret.target.template.engineVersion }}
      engineVersion: {{ $externalSecret.target.template.engineVersion }}
      {{- end }}
      {{- if $externalSecret.target.template.metadata }}
      metadata:
        {{- if $externalSecret.target.template.metadata.labels }}
        {{- with $externalSecret.target.template.metadata.labels }}
        labels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if $externalSecret.target.template.metadata.annotations }}
        {{- with $externalSecret.target.template.metadata.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- if $externalSecret.target.template.data }}
      {{- with $externalSecret.target.template.data }}
      data:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if $externalSecret.target.template.templateFrom }}
      templateFrom:
      {{- range $templateFrom := $externalSecret.target.template.templateFrom }}
      {{- if $templateFrom.configMap }}
        - configMap:
            name: {{ $templateFrom.configMap.name }}
            items:
            {{ range $templateFromConfigMapItems := $templateFrom.configMap.items }}
              - key: {{ $templateFromConfigMapItems.key }}
            {{- end }}
      {{- end }}
      {{- if $templateFrom.secret }}
        - secret:
            name: {{ $templateFrom.secret.name }}
            items:
            {{- range $templateFromSecretItems := $templateFrom.secret.items }}
              - key: {{ $templateFromSecretItems.key }}
            {{- end }}
      {{- end }}
      {{- if $templateFrom.scope }}
        scope: {{ $templateFrom.scope }}
      {{- end }}
      {{- if $templateFrom.target }}
        target: {{ $templateFrom.target }}
      {{- end }}
      {{- if $templateFrom.literal }}
        literal: {{ $templateFrom.literal }}
      {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- if $externalSecret.target.immutable }}
    immutable: {{ $externalSecret.target.immutable }}
    {{- end }}
  {{- end }}
  refreshInterval: {{ $externalSecret.refreshInterval | default "1h" }}
  {{- if $externalSecret.data }}
  data:
  {{- range $externalSecretData := $externalSecret.data }}
    - secretKey: {{ $externalSecretData.secretKey }}
      remoteRef:
        key: {{ $externalSecretData.remoteRef.key }}
        {{- if $externalSecretData.remoteRef.metadataPolicy }}
        metadataPolicy: {{ $externalSecretData.remoteRef.metadataPolicy | default "None" }}
        {{- end }}
        {{- if $externalSecretData.remoteRef.property }}
        property: {{ $externalSecretData.remoteRef.property }}
        {{- end }}
        {{- if $externalSecretData.remoteRef.version }}
        version: {{ $externalSecretData.remoteRef.version }}
        {{- end }}
        {{- if $externalSecretData.remoteRef.conversionStrategy }}
        conversionStrategy: {{ $externalSecretData.remoteRef.conversionStrategy }}
        {{- end }}
        {{- if $externalSecretData.remoteRef.decodingStrategy }}
        decodingStrategy: {{ $externalSecretData.remoteRef.decodingStrategy }}
        {{- end }}
      {{- if $externalSecretData.sourceRef }}
      sourceRef:
        {{- if $externalSecretData.sourceRef.storeRef }}
        storeRef:
          name: {{ $externalSecretData.sourceRef.storeRef.name }}
          kind: {{ $externalSecretData.sourceRef.storeRef.kind | default "SecretStore" }}
        {{- end }}
        {{- if $externalSecretData.sourceRef.generatorRef }}
        generatorRef:
          apiVersion: {{ $externalSecretData.sourceRef.generatorRef.apiVersion }}
          kind: {{ $externalSecretData.sourceRef.generatorRef.kind }}
          name: {{ $externalSecretData.sourceRef.generatorRef.name }}
        {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- if $externalSecret.dataFrom }}
  dataFrom:
  {{- range $externalSecretDataFrom := $externalSecret.dataFrom }}
    {{- if $externalSecretDataFrom.sourceRef }}
    - sourceRef:
        {{- if $externalSecretDataFrom.sourceRef.storeRef }}
        storeRef:
          name: {{ $externalSecretDataFrom.sourceRef.storeRef.name }}
          kind: {{ $externalSecretDataFrom.sourceRef.storeRef.kind | default "SecretStore" }}
        {{- end }}
        {{- if $externalSecretDataFrom.sourceRef.generatorRef }}
        generatorRef:
          apiVersion: {{ $externalSecretDataFrom.sourceRef.generatorRef.apiVersion }}
          kind: {{ $externalSecretDataFrom.sourceRef.generatorRef.kind }}
          name: {{ $externalSecretDataFrom.sourceRef.generatorRef.name }}
        {{- end }}
    {{- end }}
    {{- if and $externalSecretDataFrom.extract $externalSecretDataFrom.rewrite }}
    - extract:
        key: {{ $externalSecretDataFrom.extract.key }}
        {{- if $externalSecretDataFrom.extract.metadataPolicy }}
        metadataPolicy: {{ $externalSecretDataFrom.extract.metadataPolicy | default "None" }}
        {{- end }}
        {{- if $externalSecretDataFrom.extract.property }}
        property: {{ $externalSecretDataFrom.extract.property }}
        {{- end }}
        {{- if $externalSecretDataFrom.extract.version }}
        version: {{ $externalSecretDataFrom.extract.version }}
        {{- end }}
        {{- if $externalSecretDataFrom.extract.conversionStrategy }}
        conversionStrategy: {{ $externalSecretDataFrom.extract.conversionStrategy }}
        {{- end }}
        {{- if $externalSecretDataFrom.extract.decodingStrategy }}
        decodingStrategy: {{ $externalSecretDataFrom.extract.decodingStrategy }}
        {{- end }}
      rewrite:
      {{- range $externalSecretDataFromRewrite := $externalSecretDataFrom.rewrite }}
        - regexp:
            source: {{ $externalSecretDataFromRewrite.source }}
            target: {{ $externalSecretDataFromRewrite.target }}
      {{- end }}
    {{- end }}
    {{- if and $externalSecretDataFrom.find $externalSecretDataFrom.rewrite }}
    - find:
        {{- if $externalSecretDataFrom.find.path }}
        path: {{ $externalSecretDataFrom.find.path }}
        {{- end }}
        {{- if $externalSecretDataFrom.find.name }}
        name: {{ $externalSecretDataFrom.find.name }}
        {{- end }}
        {{- if $externalSecretDataFrom.find.tags }}
        {{- with $externalSecretDataFrom.find.tags }}
        tags:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if $externalSecretDataFrom.find.conversionStrategy }}
        conversionStrategy: {{ $externalSecretDataFrom.find.conversionStrategy }}
        {{- end }}
        {{- if $externalSecretDataFrom.find.decodingStrategy }}
        decodingStrategy: {{ $externalSecretDataFrom.find.decodingStrategy }}
        {{- end }}
      rewrite:
      {{- range $externalSecretDataFromRewrite := $externalSecretDataFrom.rewrite }}
        - regexp:
            source: {{ $externalSecretDataFromRewrite.source }}
            target: {{ $externalSecretDataFromRewrite.target }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
