{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  {{- if .Values.secretStore.labels }}
  {{- with .Values.secretStore.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.secretStore.annotations }}
  {{- with .Values.secretStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.secretStore.namespace }}
  namespace: {{ .Values.secretStore.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
spec:
  {{- if .Values.secretStore.controller }}
  controller: {{ .Values.secretStore.controller }}
  {{- end }}
  {{- if .Values.secretStore.provider }}
  {{- with .Values.secretStore.provider }}
  provider:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.secretStore.retrySettings }}
  {{- with .Values.secretStore.retrySettings }}
  retrySettings:
    maxRetries: {{ .maxRetries }}
    retryInterval: {{ .retryInterval | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.secretStore.refreshInterval }}
  refreshInterval: {{ .Values.secretStore.refreshInterval }}
  {{- end }}
{{- end }}
